# Generated by Django 3.2.6 on 2021-09-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0016_auto_20210925_2154'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
