# Generated by Django 3.2.6 on 2021-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
