# Generated by Django 3.2.6 on 2021-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0002_auto_20210831_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(null=True),
        ),
    ]
