# Generated by Django 3.2.6 on 2021-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0005_rename_blog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='saved', to='blogmain.BlogPost'),
        ),
    ]
