# Generated by Django 3.2.6 on 2021-09-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('blogmain', '0014_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
